### ISSUE TITLE
New Language from Scratch

### ISSUE THREAD

**Issue by SK1Y101** [Skiylia-Lang/Verboscript#1]
So: VerboseLang:
doesn't have an actual name, or anything really.

A lot of things need to be decided before any code can be laid down, such as:

- [ ] Naming:
  - [ ] What is this language actually called?
  - [ ] What file extension does it use?
- [ ] Syntax:
  - [ ] How does one declare variables
  - [ ] What about loops
  - [ ] or conditionals?
- [ ] Examples
  - [ ] Maybe a few examples of VerboseLang next to Python to highlight the difference
  - [ ] This also allows unit Testing to be performed
- [ ] Technical details
  - [ ] Is this language [Compiled](https://en.wikipedia.org/wiki/Compiled_language), or [Interpreted](https://en.wikipedia.org/wiki/Interpreter_(computing)), or somewhere inbetween?
  - [ ] Dynamic or static typing?
  - [ ] Bytecode, Tree-walk, or JIT?

And a whole host of other details I haven't thought to type yet.

Some resources to help with building this:
[Crafting Interpreters](http://craftinginterpreters.com/contents.html)
[My own (ongoing) creation](https://skiylia-lang.github.io/)
Any others welcome:

**Comment by SK1Y101** [comment]
More syntax ideas referenced in #3 #4 #5 #6 #7

**Comment by SK1Y101** [comment]
Could call it `Verboscript` with the `.vrbo` extension?

**Comment by Amritanshu02** [comment]
Hello! I would like to work upon this issue, could you suggest me where to start ?

**Comment by SK1Y101** [comment]
Well I'm currently looking through a lot of programing syntax and coming up with their equivalent in plain english, So if you wanted to suggest alternatives on any of their issues, or find new syntax examples not listed, that would probably be the best place to start.

There is a wiki page [here](https://github.com/Skiylia-Lang/Verboscript/wiki/Example-Syntax) of all the examples, though none have been decided concretely.

The project is still in it's infancy though, so all of the time spend is just planing and idea brainstorming.
